name: Package VSCode Plugin

on:
  push:

jobs:
  prepare:
    name: Build Native Dependencies
    strategy:
      matrix:
        kind: ['linux', 'macos', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            folder_name: Linux 
          - kind: macos
            os: macOS-latest
            folder_name: Darwin
          - kind: windows
            os: windows-latest
            folder_name: Windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm install

    - name: Compile
      working-directory: ${{ github.workspace }}/scripts
      run: node rebuildElectron.js

    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.folder_name }}
        path: ${{ github.workspace }}/out/${{ matrix.folder_name }}
        retention-days: 1

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - uses: actions/checkout@v2

    - name: Retrieve Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: Linux
        path: ${{ github.workspace }}/out/Linux

    - name: Retrieve macOS Artifact
      uses: actions/download-artifact@v2
      with:
        name: Darwin
        path: ${{ github.workspace }}/out/Darwin

    - name: Retrieve Windows Artifact
      uses: actions/download-artifact@v2
      with:
        name: Windows
        path: ${{ github.workspace }}/out/Windows

    - name: Package
      run: |
        mkdir -p ${{ github.workspace }}/dist
        cp ${{ github.workspace }}/out/Darwin/libcblite* ${{ github.workspace }}/dist
        cp ${{ github.workspace }}/out/Windows/cblite.dll ${{ github.workspace }}/dist
        npm install
        npm run package

    # - name: Publish
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: "vscode-cblite*"