name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - name: Run tests
        run: npm test
        if: runner.os != 'Linux'
